In [4]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import numpy as np
import torch

In [5]:
# array
arr = [[1,2],[3,4]]
np.array(arr)
torch.Tensor(arr)

array([[1, 2],
       [3, 4]])

tensor([[1., 2.],
        [3., 4.]])

In [8]:
# matrixs
np.ones((2,2))
torch.ones((2,2))
np.random.rand(2,2)
torch.rand(2,2)

array([[1., 1.],
       [1., 1.]])

tensor([[1., 1.],
        [1., 1.]])

array([[0.80121094, 0.01649234],
       [0.43773113, 0.21167037]])

tensor([[0.4615, 0.1564],
        [0.4149, 0.8328]])

In [10]:
#seed
np.random.seed(0)
np.random.rand(2,2)
torch.manual_seed(0)
torch.rand(2,2)

# if torch.cuda.is_avilable():
#    torch.cuda.manual_seeds(0)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

# numpy to torch

In [17]:
np_array = np.ones((2,2))
print(type(np_array))

<class 'numpy.ndarray'>


In [16]:
torch_tensor = torch.from_numpy(np_array)
torch_tensor
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

<class 'torch.Tensor'>


the conversion only supports:
1. double
2. float
3. int64,32,uint8

In [21]:
torch.from_numpy(np.ones((2,2), dtype=np.uint8))
torch.from_numpy(np.ones((2,2), dtype=np.int32))
torch.from_numpy(np.ones((2,2), dtype=np.int64))
torch.from_numpy(np.ones((2,2), dtype=np.float))
torch.from_numpy(np.ones((2,2), dtype=np.double))

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

tensor([[1, 1],
        [1, 1]])

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

# torch to numpy

In [23]:
torch_tensor = torch.ones(2,2)
type(torch_tensor)
torch_tensor.numpy()

torch.Tensor

array([[1., 1.],
       [1., 1.]], dtype=float32)

# operations

In [37]:
# flatting
a = torch.ones(2,2)
a
a.size()
a.view(4)
a.view(4).size()

tensor([[1., 1.],
        [1., 1.]])

torch.Size([2, 2])

tensor([1., 1., 1., 1.])

torch.Size([4])

In [38]:
# element-wise
b = torch.ones(2,2)
c = a + b
c
torch.add(a,b)
# inplace addition
c
c.add_(a)
c

tensor([[2., 2.],
        [2., 2.]])

tensor([[2., 2.],
        [2., 2.]])

tensor([[2., 2.],
        [2., 2.]])

tensor([[3., 3.],
        [3., 3.]])

tensor([[3., 3.],
        [3., 3.]])

In [39]:
# element-wise  substraction
a - b 
a.sub(b)
# inplace subtraction
a
a.sub_(b)
a

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

In [40]:
# element-wise multiment
a = torch.ones(2,2)
b = torch.zeros(2,2)
a * b
torch.mul(a,b)
# inplace multipe
a
a.mul_(b)
a

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

In [41]:
# element-wise devision
a = torch.ones(2,2)
b = torch.zeros(2,2)
b / a
torch.div(b, a)
# inplace multipe
b
b.mul_(a)
b

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

# STATS operation

In [43]:
# mean
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()
a.mean(dim=0)
a.mean(dim=1)

torch.Size([10])

tensor(5.5000)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [45]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()
a.mean(dim=0)
a.mean(dim=1)

torch.Size([2, 10])

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

tensor([5.5000, 5.5000])

In [47]:
#standrad
a.std(dim=1)

tensor([3.0277, 3.0277])