In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [11]:
import torch
import numpy as np
from torch.autograd import Variable

In [6]:
a = Variable(torch.ones(2,2), requires_grad=True)
b = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
a + b
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [41]:
x = Variable(torch.ones(1,2), requires_grad=True)
y = 5 * (x + 1) **2 
y

tensor([[20., 20.]], grad_fn=<MulBackward0>)

In [42]:
o = 0.5 * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [39]:
o.backward(retain_graph=True)
x.grad

tensor([[10., 10.]])

In [43]:
o.backward(torch.FloatTensor([1.0,1.0]))
x.grad

tensor([[20., 20.]])